In [1]:
import pandas as pd
import numpy as np 
df = pd.read_csv(r"C:\Users\arvin\OneDrive\Documents\yotube datasets.csv")
yt = df
yt

,Video_Id,Trending_Timing,Title Of The Video,Channel_title,category_id,publish_time,Tages,views,likes,dislikes,Comment_on_Video,Thumbnail_Of_Video,Comment,Rating_Disabled,Video_removed,Description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals
40945,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN
40946,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...
40947,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...
40948,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...

In [4]:
af = pd.read_csv(r'C:\Users\arvin\Downloads\DataSets\archive (3)\yotube datasets.csv')
af.shape

(40949, 16)

In [18]:
yt.describe

<bound method NDFrame.describe of           Video_Id Trending_Timing  \
0      2kyS6SvSYSE        17.14.11
1      1ZAPwfrtAFY        17.14.11
2      5qpjK5DgCt4        17.14.11
3      puqaWrEC7tY        17.14.11
4      d380meD0W0M        17.14.11
...            ...             ...
40944  BZt0qjTWNhw        18.14.06
40945  1h7KV2sjUWY        18.14.06
40946  D6Oy4LfoqsU        18.14.06
40947  oV0zkMe1K8s        18.14.06
40948  ooyjaVdt-jA        18.14.06

                                      Title Of The Video  \
0                     WE WANT TO TALK ABOUT OUR MARRIAGE
1      The Trump Presidency: Last Week Tonight with J...
2      Racist Superman | Rudy Mancuso, King Bach & Le...
3                       Nickelback Lyrics: Real or Fake?
4                               I Dare You: GOING BALD!?
...                                                  ...
40944                       The Cat Who Caught the Laser
40945                         True Facts : Ant Mutualism
40946  I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...
40947                How Black Panther Should Have Ended
40948  Official Call of Duty®: Black Ops 4 — Multipla...

                  Channel_title  category_id              publish_time  \
0                  CaseyNeistat           22  2017-11-13T17:13:01.000Z
1               LastWeekTonight           24  2017-11-13T07:30:00.000Z
2                  Rudy Mancuso           23  2017-11-12T19:05:24.000Z
3         Good Mythical Morning           24  2017-11-13T11:00:04.000Z
4                      nigahiga           24  2017-11-12T18:01:41.000Z
...                         ...          ...                       ...
40944             AaronsAnimals           15  2018-05-18T13:00:04.000Z
40945                  zefrank1           22  2018-05-18T01:00:06.000Z
40946                Brad Mondo           24  2018-05-18T17:34:22.000Z
40947  How It Should Have Ended            1  2018-05-17T17:00:04.000Z
40948              Call of Duty           20  2018-05-17T17:09:38.000Z

                                                   Tages     views   likes  \
0                                        SHANtell martin    748374   57527
1      last week tonight trump presidency|"last week ...   2418783   97185
2      racist superman|"rudy"|"mancuso"|"king"|"bach"...   3191434  146033
3      rhett and link|"gmm"|"good mythical morning"|"...    343168   10172
4      ryan|"higa"|"higatv"|"nigahiga"|"i dare you"|"...   2095731  132235
...                                                  ...       ...     ...
40944  aarons animals|"aarons"|"animals"|"cat"|"cats"...   1685609   38160
40945                                             [none]   1064798   60008
40946  I gave safiya nygaard a perfect hair makeover ...   1066451   48068
40947  Black Panther|"HISHE"|"Marvel"|"Infinity War"|...   5660813  192957
40948      call of duty|"cod"|"activision"|"Black Ops 4"  10306119  357079

       dislikes  Comment_on_Video  \
0          2966             15954
1          6146             12703
2          5339              8181
3           666              2146
4          1989             17518
...         ...               ...
40944      1385              2657
40945       382              3936
40946      1032              3992
40947      2846             13088
40948    212976            144795

                                   Thumbnail_Of_Video  Comment  \
0      https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg    False
1      https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg    False
2      https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg    False
3      https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg    False
4      https://i.ytimg.com/vi/d380meD0W0M/default.jpg    False
...                                               ...      ...
40944  https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg    False
40945  https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg    False
40946  https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg    False
40947  https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg    False
40948  https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg    False

       Rating_Disabled  Video_removed   \
0                False           False
1                False           False
2                False           False
3                False           False
4                False           False
...                ...             ...
40944            False           False
40945            False           False
40946            False           False
40947            False           False
40948            False           False

                                             Description
0      SHANTELL'S CHANNEL - https://www.youtube.com/s...
1      One year after the presidential election, John...
2      WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3      Today we find out if Link is a Nickelback amat...
4      I know it's been a while since we did this sho...
...                                                  ...
40944     The Cat Who Caught the Laser - Aaron's Animals
40945                                                NaN
40946  I had so much fun transforming Safiyas hair in...
40947  How Black Panther Should Have EndedWatch More ...
40948  Call of Duty: Black Ops 4 Multiplayer raises t...

[40949 rows x 16 columns]>

In [21]:
yt.columns

Index(['Video_Id', 'Trending_Timing', 'Title Of The Video', 'Channel_title',
       'category_id', 'publish_time', 'Tages', 'views', 'likes', 'dislikes',
       'Comment_on_Video', 'Thumbnail_Of_Video', 'Comment', 'Rating_Disabled',
       'Video_removed ', 'Description'],
      dtype='str')

In [22]:
yt.shape

(40949, 16)

In [25]:
yt.dtypes

Video_Id                str
Trending_Timing         str
Title Of The Video      str
Channel_title           str
category_id           int64
publish_time            str
Tages                   str
views                 int64
likes                 int64
dislikes              int64
Comment_on_Video      int64
Thumbnail_Of_Video      str
Comment                bool
Rating_Disabled        bool
Video_removed          bool
Description             str
dtype: object

In [28]:
yt.isnull().sum()

Video_Id                0
Trending_Timing         0
Title Of The Video      0
Channel_title           0
category_id             0
publish_time            0
Tages                   0
views                   0
likes                   0
dislikes                0
Comment_on_Video        0
Thumbnail_Of_Video      0
Comment                 0
Rating_Disabled         0
Video_removed           0
Description           570
dtype: int64

In [3]:
yt[yt.duplicated()].value_counts()

Video_Id     Trending_Timing  Title Of The Video                                                                                 Channel_title         category_id  publish_time              Tages                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         views     likes   dislikes  Comment_on_Video  Thumbnail_Of_Video                              Comment  Rating_Disabled  Video_removed   Description
QBL8IRJ5yHU  18.15.05         Why I'm So Scared (being myself and crying too much)                                               grav3yardgirl         26           2018-05-14T19:00:01.000Z  beauty|"how to"|"makeup"|"howto"|"style"|"fashion"|"summer"|"spring"|"new"|"clothes"|"clothing"|"bunny"|"follow me around"|"target"|"shop"|"shopping"|"cosmetics"|"funny"|"haul"|"store"|"look"|"silly"|"cute"|"eye"|"eyes"|"iphone"|"vlog"|"grav3yardgirl"|"as seen on tv"|"infomercial"|"does it work"|"nail"|"nails"|"bed bath & beyond"|"ulta"|"2018"|"cheap makeup"|"makeup shopping"|"clearance"|"clearance makeup"|"toys r us"|"closing"|"store closing"|"dior"|"dior handbag"|"luxury"|"designer"                                                     1469627   188652  3124      33032             https://i.ytimg.com/vi/QBL8IRJ5yHU/default.jpg  False    False            False           I will never be able to say Thank You enough... Thank you for being my family.➡ CLICK HERE -  http://bit.ly/GiveAGatorItsWings➡ SUBSCRIBE TO MY 2ND CHANNEL!: http://bit.ly/2hsXpQd➡ ADD ME ON SNAPCHAT: BM885_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _♡ GRAV3YARD CURL COLLECTION: http://bit.ly/Grav3yardCurl♡ Entire Set - http://bit.ly/Grav3yardCurlSet♡ Gator Hairdryer: http://bit.ly/GatorHairdryer♡ Gator Flat Iron: http://bit.ly/GatorFlatIron♡ Gator Clipless Curler: http://bit.ly/GatorCliplessCurler♡ INSTAGRAM: http://bit.ly/1wdGBwS  ♡ TWITTER: http://twitter.com/grav3yardgirl♡ FACEBOOK: http://bit.ly/2ktztLnyou might enjoy these other videos?EDIBLE JELLO GLASSES: http://bit.ly/EdibleJelloGlasses$500 Designer Mystery Box: http://bit.ly/LuxuryMysteryBox$900 Ebay 90s Mystery Box: http://bit.ly/90sMysteryBoxLucky Bag 2018: http://bit.ly/LuckyBag2018Grav3yardgirlMaking a MINIATURE Happy Meal: http://bit.ly/MiniatureHappyMealWUBBLE BUBBLE BALL: http://bit.ly/WubbleBubbleGrav3yardgirlSNO CONE SLIME DIY: http://bit.ly/SnoConeSlimeFishbowl Slime DIY: http://bit.ly/FishbowlSlime♡ EVERYTIME YOU SUBSCRIBE, A GATOR GETS HIS WINGS! ♡FTC- I am not being paid by any of the mentioned companies or designers to make this video. The views in this video are strictly my own and I am not affiliated with any of these companies.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
t4pRQ0jn23Q  18.15.05         YoungBoy Never Broke Again Goes Sneaker Shopping With Complex                                      Complex               24           2018-05-14T14:00:03.000Z  sneakerhead|"complex"|"complex originals"|"sneakers"|"news"|"entertainment"|"current affairs"|"young man"|"culture"|"complex tv"|"complex media"|"sneaker shopping with"|"sneaker shopping"|"sneaker shopping on complex"|"youngboy never broke again"|"young boy never broke again"|"youngboy nba 2018"|"youngboy nba"|"joe la puma"|"air jordan 3 powder blue"|"air jordan 11 space jams"|"air jordan 8 retro ovo"|"until death call my name nba"|"until death call my name youngboy never broke again"|"nike"                                              1199587   49709   2380      7261              https://i.ytimg.com/vi/t4pRQ0jn23Q/default.jpg  False    False            False           YoungBoy Never Broke Again goes Sneaker Shopping with Complex's Joe La Puma at Stadium Goods in New York City and talks about wearing Air Jordans growing up, never wearing the same outfit twice, and wanting to start his own sneaker brand.NOTE: This episode was shot on February, 22, 2018.Subscribe to Complex on YouTube: https://goo.gl/43ac5wCheck out more of Complex here:http://www.complex.comhttps://twitter.com/Complexhttps://www.facebook.com/complexhttp://instagram.com/complexhttps://plus.google.com/+complex/COMPLEX is a community of creators and curators, armed with the Internet, committed to surfacing and sharing the voices and conversations that define our new America. Our videos exemplify convergence culture, exploring topics that include music, sneakers, style, sports and pop culture through original shows and Complex News segments. Featuring your favorite celebrities, authoritative commentary, and a unique voice, our videos make culture pop.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
j4KvrAUjn6c  18.15.05         WE MADE OUR MOM CRY...HER DREAM CAME TRUE!                                                         Lucas and Marcus      24           2018-05-13T18:03:56.000Z  Lucas and Marcus|"Marcus and Lucas"|"Dobre"|"Dobre Twins"|"Dobre Brothers"|"The Dobre Brothers"|"Dobre Brothers YouTube"|"Lucas and Marcus pranks"|"Dobre brothers gymnastics"|"Dobre brothers pranks"|"Gymnastics"|"Dance"|"Challenges"|"Music"|"Rap"|"Pranks"|"Grocery Store"|"Cars"|"Reactions"|"Makeup"|"Make-up"|"Games"|"Food"|"Family"|"Collabs"|"Animals"|"pg"|"family friendly"|"guava juice"|"the ace family"                                                                                                                                       3906727   77378   12160     15874             https://i.ytimg.com/vi/j4KvrAUjn6c/default.jpg  False    False            False           BEST MOM EVER! WANT TO SEE US IN NYC & NJ?!BUY TIX HERE! ➨ http://bit.ly/DobreTour WE POST TUESDAY,THURSDAY, & SUNDAY!TURN OUR POST NOTIFICATIONS ON FOR A SHOUTOUT!SUBSCRIBE TO THE DOBRE VLOG CHANNEL! https://www.youtube.com/channel/UCC3OGYxHwV8pB5yLobw9KdASUBSCRIBE TO THE LUCAS AND MARCUS CHANNEL!https://www.youtube.com/user/TwiNboTzVids Lucas's Social Media  Instagram: https://www.instagram.com/lucas_dobre/Twitter: https://twitter.com/dobrelucasFacebook: https://www.facebook.com/dobrelucas/Snapchat: lucas_dobreMusical.ly: DobreTwins Marcus's Social Media  Instagram: https://www.instagram.com/marcusdobreTwitter: https://twitter.com/dobremarcusFacebook: https://www.facebook.com/marcusdobre/Snapchat: marcusdobre1Musical.ly: DobretwinsFollow the Dobre Brothers: Instagram: https://www.instagram.com/dobrebrothers/BIZ - dobrebrothersmgmt@gmail.com THANKS FOR WATCHING!WE MADE OUR MOM CRY...HER DREAM CAME TRUE!https://www.youtube.com/user/TwiNboTzVids                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1

In [ ]:
yt[yt.duplicated()]

In [ ]:
# highest Watched or highest views on Youtube Channel 
Max = yt['views'].max()
yt[yt['views'] == Max]

,Video_Id,Trending_Timing,Title Of The Video,Channel_title,category_id,publish_time,Tages,views,likes,dislikes,Comment_on_Video,Thumbnail_Of_Video,Comment,Rating_Disabled,Video_removed,Description
38547,VYOjWnS4cMY,18.02.06,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06T04:00:07.000Z,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",225211923,5023450,343541,517232,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...

In [ ]:
# Least watched video in the Youtube 
Min = yt['views'].min()
yt[yt['views'] == Min]

,Video_Id,Trending_Timing,Title Of The Video,Channel_title,category_id,publish_time,Tages,views,likes,dislikes,Comment_on_Video,Thumbnail_Of_Video,Comment,Rating_Disabled,Video_removed,Description
14335,y6KYFcta4SE,18.26.01,"1 dead, others injured after Ky. school shooting",Newsy,25,2018-01-23T15:30:01.000Z,"shooting|""kentucky""|""breaking news""|""u.s. news...",549,9,0,5,https://i.ytimg.com/vi/y6KYFcta4SE/default.jpg,False,False,False,Kentucky Gov. Matt Bevin confirmed there was a...

In [13]:
#Top5 most viewed video in Yotube channel 
yt.nlargest(5, 'views')

,Video_Id,Trending_Timing,Title Of The Video,Channel_title,category_id,publish_time,Tages,views,likes,dislikes,Comment_on_Video,Thumbnail_Of_Video,Comment,Rating_Disabled,Video_removed,Description
38547,VYOjWnS4cMY,18.02.06,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06T04:00:07.000Z,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",225211923,5023450,343541,517232,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
38345,VYOjWnS4cMY,18.01.06,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06T04:00:07.000Z,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",220490543,4962403,338105,512337,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
38146,VYOjWnS4cMY,18.31.05,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06T04:00:07.000Z,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",217750076,4934188,335462,509799,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
37935,VYOjWnS4cMY,18.30.05,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06T04:00:07.000Z,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",210338856,4836448,326902,501722,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
37730,VYOjWnS4cMY,18.29.05,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06T04:00:07.000Z,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",205643016,4776680,321493,496211,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...

In [14]:
# Top5 least Watched video on the Youtube Channel
yt.nsmallest(5, 'views')

,Video_Id,Trending_Timing,Title Of The Video,Channel_title,category_id,publish_time,Tages,views,likes,dislikes,Comment_on_Video,Thumbnail_Of_Video,Comment,Rating_Disabled,Video_removed,Description
14335,y6KYFcta4SE,18.26.01,"1 dead, others injured after Ky. school shooting",Newsy,25,2018-01-23T15:30:01.000Z,"shooting|""kentucky""|""breaking news""|""u.s. news...",549,9,0,5,https://i.ytimg.com/vi/y6KYFcta4SE/default.jpg,False,False,False,Kentucky Gov. Matt Bevin confirmed there was a...
14563,y6KYFcta4SE,18.27.01,"1 dead, others injured after Ky. school shooting",Newsy,25,2018-01-23T15:30:01.000Z,"shooting|""kentucky""|""breaking news""|""u.s. news...",554,9,0,4,https://i.ytimg.com/vi/y6KYFcta4SE/default.jpg,False,False,False,Kentucky Gov. Matt Bevin confirmed there was a...
14782,y6KYFcta4SE,18.28.01,"1 dead, others injured after Ky. school shooting",Newsy,25,2018-01-23T15:30:01.000Z,"shooting|""kentucky""|""breaking news""|""u.s. news...",559,9,0,4,https://i.ytimg.com/vi/y6KYFcta4SE/default.jpg,False,False,False,Kentucky Gov. Matt Bevin confirmed there was a...
14531,dQMZLXaa1L8,18.27.01,Artwork Forge,Palo Alto Online,17,2018-01-10T23:53:56.000Z,[none],658,1,0,0,https://i.ytimg.com/vi/dQMZLXaa1L8/default.jpg,False,False,False,Artwork Forge II - an art installation created...
546,#NAME?,17.16.11,Coach Taggart Monday Presser Ahead of Arizona,GoDucksdotcom,17,2017-11-13T20:41:45.000Z,"Oregon|""Ducks""|""college athletics""|""college fo...",687,10,2,5,https://i.ytimg.com/vi/-JVITToppE0/default.jpg,False,False,False,Coach Taggart addresses the media ahead of the...

In [21]:
# Average views on youtube in channel 
yt['views'].mean()

np.float64(2360784.6382573447)

In [22]:
#Median Views on Youtube Channel 
yt['views'].median()

np.float64(681861.0)

In [ ]:
# Sum of views in the youtube Channel 
yt['views'].sum()

np.int64(96671770152)

In [ ]:
#Most likes video in the Youtube Channel 
like = yt['likes'].max()
yt[yt['likes'] == like]

,Video_Id,Trending_Timing,Title Of The Video,Channel_title,category_id,publish_time,Tages,views,likes,dislikes,Comment_on_Video,Thumbnail_Of_Video,Comment,Rating_Disabled,Video_removed,Description
38273,7C2z4GqqS5E,18.01.06,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,10,2018-05-18T09:00:02.000Z,"BIGHIT|""빅히트""|""방탄소년단""|""BTS""|""BANGTAN""|""방탄""|""FAK...",123010920,5613827,206892,1228655,https://i.ytimg.com/vi/7C2z4GqqS5E/default.jpg,False,False,False,BTS (방탄소년단) 'FAKE LOVE' Official MVDirector : ...

In [ ]:
#Top5 liked videos in the Youtube Channel 
yt.nlargest(5, 'likes')

,Video_Id,Trending_Timing,Title Of The Video,Channel_title,category_id,publish_time,Tages,views,likes,dislikes,Comment_on_Video,Thumbnail_Of_Video,Comment,Rating_Disabled,Video_removed,Description
38273,7C2z4GqqS5E,18.01.06,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,10,2018-05-18T09:00:02.000Z,"BIGHIT|""빅히트""|""방탄소년단""|""BTS""|""BANGTAN""|""방탄""|""FAK...",123010920,5613827,206892,1228655,https://i.ytimg.com/vi/7C2z4GqqS5E/default.jpg,False,False,False,BTS (방탄소년단) 'FAKE LOVE' Official MVDirector : ...
38072,7C2z4GqqS5E,18.31.05,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,10,2018-05-18T09:00:02.000Z,"BIGHIT|""빅히트""|""방탄소년단""|""BTS""|""BANGTAN""|""방탄""|""FAK...",121219886,5595203,205565,1225326,https://i.ytimg.com/vi/7C2z4GqqS5E/default.jpg,False,False,False,BTS (방탄소년단) 'FAKE LOVE' Official MVDirector : ...
37861,7C2z4GqqS5E,18.30.05,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,10,2018-05-18T09:00:02.000Z,"BIGHIT|""빅히트""|""방탄소년단""|""BTS""|""BANGTAN""|""방탄""|""FAK...",115664850,5530568,200995,1213172,https://i.ytimg.com/vi/7C2z4GqqS5E/default.jpg,False,False,False,BTS (방탄소년단) 'FAKE LOVE' Official MVDirector : ...
37655,7C2z4GqqS5E,18.29.05,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,10,2018-05-18T09:00:02.000Z,"BIGHIT|""빅히트""|""방탄소년단""|""BTS""|""BANGTAN""|""방탄""|""FAK...",111882133,5486349,197638,1204867,https://i.ytimg.com/vi/7C2z4GqqS5E/default.jpg,False,False,False,BTS (방탄소년단) 'FAKE LOVE' Official MVDirector : ...
37453,7C2z4GqqS5E,18.28.05,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,10,2018-05-18T09:00:02.000Z,"BIGHIT|""빅히트""|""방탄소년단""|""BTS""|""BANGTAN""|""방탄""|""FAK...",107756615,5439015,194172,1197130,https://i.ytimg.com/vi/7C2z4GqqS5E/default.jpg,False,False,False,BTS (방탄소년단) 'FAKE LOVE' Official MVDirector : ...

In [ ]:
#Average likes in the Youtube Channel 
yt['likes'].mean()

np.float64(74266.7024347359)

In [30]:
yt[['views', 'likes']].corr()

          views     likes
views  1.000000  0.849177
likes  0.849177  1.000000

In [47]:
yt['Channel_title'].value_counts().idxmax()

'ESPN'

In [52]:
#top 10 Channel by number of videos uploaded 

yt['Channel_title'].value_counts(10)

Channel_title
ESPN                                      0.004957
The Tonight Show Starring Jimmy Fallon    0.004811
Vox                                       0.004713
TheEllenShow                              0.004713
Netflix                                   0.004713
                                            ...
Owen Harvey                               0.000024
King Princess                             0.000024
David Seymour                             0.000024
UMF TV                                    0.000024
RiceGum                                   0.000024
Name: proportion, Length: 2207, dtype: float64

In [56]:
# Highest views by a channel 
yt.groupby('Channel_title')['views'].sum().sort_values(ascending=False).head(1)

Channel_title
ChildishGambinoVEVO    3758488765
Name: views, dtype: int64

In [ ]:
#Which channel has highest average in this Datasets
yt.groupby('Channel_title')['views'].mean().sort_values(ascending=False).head(1)

Channel_title
ChildishGambinoVEVO    150339550.6
Name: views, dtype: float64

In [65]:
#every Channel total views 
yt.groupby('Channel_title')['views'].sum().sort_values(ascending=False)

Channel_title
ChildishGambinoVEVO                     3758488765
ibighit                                 2235906679
Dude Perfect                            1870085178
Marvel Entertainment                    1808998971
ArianaGrandeVevo                        1576959172
                                           ...
CHauserable                                   1807
Total Combat                                  1722
OjO Commuter Scooter by OjO Electric          1706
GoDucksdotcom                                 1391
90s Commercials                                773
Name: views, Length: 2207, dtype: int64

In [ ]:
#Each Channel total likes in the Datasets 
yt.groupby('Channel_title')['likes'].sum().sort_values(ascending=False)

Channel_title
ibighit                 199247121
ChildishGambinoVEVO      96700818
Dude Perfect             60275557
Marvel Entertainment     55873344
ArianaGrandeVevo         52170970
                          ...
Dancing On Ice                  0
Slooh                           0
Snapchat                        0
hudsonunionsociety              0
Kim Kardashian West             0
Name: likes, Length: 2207, dtype: int64

In [69]:
# Each channel and their Average views 
yt.groupby('Channel_title')['views'].mean().sort_values(ascending=False)

Channel_title
ChildishGambinoVEVO                     1.503396e+08
BeckyGVEVO                              5.914856e+07
LuisFonsiVEVO                           5.347388e+07
MalumaVEVO                              4.848487e+07
Kylie Jenner                            4.610644e+07
                                            ...
OjO Commuter Scooter by OjO Electric    8.530000e+02
Newsy                                   8.255000e+02
90s Commercials                         7.730000e+02
Palo Alto Online                        7.053333e+02
GoDucksdotcom                           6.955000e+02
Name: views, Length: 2207, dtype: float64

In [68]:
#Each Channel and their Maximum views 
yt.groupby('Channel_title')['views'].max().sort_values(ascending=False)

Channel_title
ChildishGambinoVEVO                          225211923
YouTube Spotlight                            149376127
ArianaGrandeVevo                             148689896
BeckyGVEVO                                   139334502
ibighit                                      123010920
                                               ...
University of Rochester EEOC Complainants          988
OjO Commuter Scooter by OjO Electric               917
90s Commercials                                    773
Palo Alto Online                                   745
GoDucksdotcom                                      704
Name: views, Length: 2207, dtype: int64

In [ ]:
#Every Channel and their uploaded video in their channel 
yt['Channel_title'].value_counts()

Channel_title
ESPN                                      203
The Tonight Show Starring Jimmy Fallon    197
Vox                                       193
TheEllenShow                              193
Netflix                                   193
                                         ...
Owen Harvey                                 1
King Princess                               1
David Seymour                               1
UMF TV                                      1
RiceGum                                     1
Name: count, Length: 2207, dtype: int64

In [75]:
yt

,Video_Id,Trending_Timing,Title Of The Video,Channel_title,category_id,publish_time,Tages,views,likes,dislikes,Comment_on_Video,Thumbnail_Of_Video,Comment,Rating_Disabled,Video_removed,Description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals
40945,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN
40946,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...
40947,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...
40948,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...

In [79]:
yt['engagemets'] = yt['likes']/yt['views']
yt[['views', 'likes', 'engagemets']].head()

     views   likes  engagemets
0   748374   57527    0.076869
1  2418783   97185    0.040179
2  3191434  146033    0.045758
3   343168   10172    0.029641
4  2095731  132235    0.063097

In [ ]:
# Top 10 Videos engagements 
yt.sort_values('engagemets', ascending=False).head(10)

,Video_Id,Trending_Timing,Title Of The Video,Channel_title,category_id,publish_time,Tages,views,likes,dislikes,Comment_on_Video,Thumbnail_Of_Video,Comment,Rating_Disabled,Video_removed,Description,engagemets
10200,LsoLEjrDogU,18.04.01,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04T04:49:43.000Z,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",548621,159356,2374,19455,https://i.ytimg.com/vi/LsoLEjrDogU/default.jpg,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,0.290466
608,TyHvyGVs42U,17.17.11,"Luis Fonsi, Demi Lovato - Échame La Culpa",LuisFonsiVEVO,10,2017-11-17T05:00:01.000Z,"Luis|""Fonsi""|""Demi""|""Lovato""|""Échame""|""La""|""Cu...",499946,135292,3528,12094,https://i.ytimg.com/vi/TyHvyGVs42U/default.jpg,False,False,False,"Music video by Luis Fonsi, Demi Lovato perform...",0.270613
22174,8O_MwlZ2dEg,18.07.03,j-hope 'Airplane' MV,ibighit,10,2018-03-06T15:00:10.000Z,"BIGHIT|""빅히트""|""방탄소년단""|""BTS""|""BANGTAN""|""방탄""",5275672,1401915,6268,158127,https://i.ytimg.com/vi/8O_MwlZ2dEg/default.jpg,False,False,False,j-hope 'Airplane' MV\n\n\n\nj-hope - 'Hope Wor...,0.265732
14428,9vDdx1dba6c,18.27.01,dodie - Secret For The Mad,dodieVEVO,10,2018-01-26T18:00:15.000Z,"dodie|""Secret""|""For""|""The""|""Mad""|""Ditto""|""Musi...",129130,32755,98,2964,https://i.ytimg.com/vi/9vDdx1dba6c/default.jpg,False,False,False,Directed and animated by \nHannah Jacobs - htt...,0.253659
5025,inZzcTXYowY,17.09.12,Louis Tomlinson - Miss You (Official Video),LouisTomlinsonVEVO,10,2017-12-08T16:00:04.000Z,"Louis Tomlinson|""Miss You""|""Pop""|""Syco Music""",985998,241679,793,26259,https://i.ytimg.com/vi/inZzcTXYowY/default.jpg,False,False,False,Louis Tomlinson's new single ‘Miss You’ is out...,0.245111
38352,D_6QmL6rExk,18.02.06,BTS (방탄소년단) 'FAKE LOVE' Official MV (Extended ...,ibighit,10,2018-06-01T15:00:01.000Z,"BIGHIT|""빅히트""|""방탄소년단""|""BTS""|""BANGTAN""|""방탄""|""fak...",5884233,1437859,6390,134721,https://i.ytimg.com/vi/D_6QmL6rExk/default.jpg,False,False,False,BTS (방탄소년단) 'FAKE LOVE' Official MV (Extended ...,0.244358
19780,UaAHl_m_ybk,18.23.02,5 Seconds Of Summer - Want You Back (Audio),5SOSVEVO,10,2018-02-23T00:00:01.000Z,"Seconds|""Of""|""Summer""|""Want""|""You""|""Back""|""Cap...",439056,106536,656,20575,https://i.ytimg.com/vi/UaAHl_m_ybk/default.jpg,False,False,False,Music video by 5 Seconds Of Summer performing ...,0.242648
33789,6mkLWGy6Y3k,18.10.05,Shawn Mendes: The Tour - Official Trailer,Shawn Mendes,10,2018-05-08T17:23:08.000Z,[none],332910,80118,232,5420,https://i.ytimg.com/vi/6mkLWGy6Y3k/default.jpg,False,False,False,For tickets & tour info head to: http://www.sh...,0.240660
34000,6mkLWGy6Y3k,18.11.05,Shawn Mendes: The Tour - Official Trailer,Shawn Mendes,10,2018-05-08T17:23:08.000Z,[none],355703,82016,249,5459,https://i.ytimg.com/vi/6mkLWGy6Y3k/default.jpg,False,False,False,For tickets & tour info head to: http://www.sh...,0.230574
885,K6xwB8Kkce0,17.18.11,Harry Styles - Kiwi (live in studio),HarryStylesVEVO,10,2017-11-17T13:00:02.000Z,"Columbia|""Harry Styles""|""Kiwi""|""Pop""",595598,136072,333,6292,https://i.ytimg.com/vi/K6xwB8Kkce0/default.jpg,False,False,False,'Harry Styles: Behind the Album - The Performa...,0.228463

In [ ]:
avg_eng = yt['engagemets'].mean() 
yt[yt['engagemets'] > avg_eng]

,Video_Id,Trending_Timing,Title Of The Video,Channel_title,category_id,publish_time,Tages,views,likes,dislikes,Comment_on_Video,Thumbnail_Of_Video,Comment,Rating_Disabled,Video_removed,Description,engagemets
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,0.076869
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",0.040179
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,0.045758
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,0.063097
5,gHZ1Qz0KiKM,17.14.11,2 Weeks with iPhone X,iJustine,28,2017-11-13T19:07:23.000Z,"ijustine|""week with iPhone X""|""iphone x""|""appl...",119180,9763,511,1434,https://i.ytimg.com/vi/gHZ1Qz0KiKM/default.jpg,False,False,False,Using the iPhone for the past two weeks -- her...,0.081918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40939,pcJo0tIWybY,18.14.06,SZA - Garden (Say It Like Dat) (Official Video),SZAVEVO,10,2018-05-18T14:00:04.000Z,"Garden (Say It Like Dat)|""R&B""|""SZA""|""Top Dawg...",6004782,210802,4166,15169,https://i.ytimg.com/vi/pcJo0tIWybY/default.jpg,False,False,False,SZA's CTRL available on:Apple Music - http://s...,0.035106
40943,1PhPYr_9zRY,18.14.06,BTS Plays With Puppies While Answering Fan Que...,BuzzFeed Celeb,22,2018-05-18T16:39:29.000Z,"BuzzFeed|""BuzzFeedVideo""|""Puppy Interview""|""pu...",8259128,645888,4052,62610,https://i.ytimg.com/vi/1PhPYr_9zRY/default.jpg,False,False,False,"BTS with the PPS, the puppies. These adorable ...",0.078203
40945,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,0.056356
40946,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,0.045073
40948,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,0.034647